const sampleListings = [
    {
        title: "The Goldfinch",
        description: "Donna Tartt's Pulitzer Prize-winning novel follows the life of Theo Decker after he survives a terrorist attack at a museum, taking with him a small, captivating painting called The Goldfinch. The novel explores themes of loss, survival, and the power of art",
        image: "",
        writer: "Donna Tartt",
        price: 1660,
    },
    {
        title: "The Alchemist",
        description: "Paulo Coelho's philosophical novel follows Santiago, a shepherd boy, on a journey to discover his personal legend. The story is a profound exploration of destiny, dreams, and the pursuit of one's purpose in life.",
        image: "",
        writer: "Paulo Coelho",
        price: 1420,
    },
    {
        title: "The Martian",
        description: "Andy Weir's gripping science fiction novel tells the story of Mark Watney, an astronaut stranded on Mars after a space mission goes awry. Watney's ingenuity and determination for survival make this a thrilling and humorous tale.",
        image: "",
        writer: "Andy Weir",
        price: 1350,
    },
    {
        title: "The Nightingale",
        description: "Kristin Hannah's historical novel follows the lives of two sisters in France during World War II. It explores the sacrifices, challenges, and resilience of women on the home front, offering a poignant and powerful narrative.",
        image: "",
        writer: "Kristin Hannah",
        price: 1500,
    },
    {
        title: "Norwegian Wood",
        description: "Haruki Murakami's novel is a coming-of-age story set in 1960s Tokyo. It explores themes of love, loss, and the complexities of human relationships through the experiences of the protagonist, Toru Watanabe.",
        image: "",
        writer: "Haruki Murakami",
        price: 1350,
    },
    {
        title: "Where the Crawdads Sing",
        description: "Delia Owens' novel is a compelling mystery and coming-of-age story set in the marshes of North Carolina. It follows the life of Kya Clark, the Marsh Girl, who becomes the center of a murder investigation",
        image: "",
        writer: "Delia Owens",
        price: 2200,
    },
    {
        title: "The Great Gatsby",
        description: "F. Scott Fitzgerald's classic novel is set in the Roaring Twenties and explores the themes of wealth, love, and the American Dream through the eyes of narrator Nick Carraway and the mysterious Jay Gatsby.",
        image: "",
        writer: "F.Scott Fitzgerald",
        price: 1410,
    },
    {
        title: "The Girl on the Train",
        description: "Paula Hawkins' psychological thriller revolves around the intertwined lives of three women and the mysteries that unfold as they become entangled in each other's secrets and lies.",
        image: "",
        writer: "Paula Hawkins",
        price: 1300,
    },
    {
        title: "Sapiens: A Brief History of Humankind",
        description: "Yuval Noah Harari's bestselling book provides a thought-provoking exploration of the history of the human species, from the emergence of Homo sapiens to the present day, covering key revolutions and developments.",
        image: "",
        writer: "Yuval Noah Harai",
        price: 2100,
    },
    {
        title: "The Handmaid's Tale",
        description: "Margaret Atwood's dystopian novel is set in the Republic of Gilead, where women's rights have been severely restricted. The story follows Offred, a Handmaid, as she navigates a society marked by oppression and control.",
        image: "",
        writer: "Margarat Atwood",
        price: 1330,
    },
    {
        title: "Circe",
        description: "Madeline Miller's Circe is a spellbinding novel that reimagines the story of Circe, a lesser-known character from Greek mythology. It explores themes of power, transformation, and the quest for identity as Circe discovers her own strength and place in the world.",
        image: "",
        writer: "Madeline Miller",
        price: 2250,
    },
    {
        title: "The Underground Railroad",
        description: "Colson Whitehead's novel is a powerful and imaginative exploration of slavery in America. It follows the journey of Cora, a young slave, as she escapes from a Georgia plantation and travels through a literal underground railroad seeking freedom.",
        image: "",
        writer: "Colson Whitehead",
        price: 1400,
    },
    {
        title: "The Immortal life of Henrietta Lacks",
        description: "Rebecca Skloot's nonfiction book tells the remarkable and true story of Henrietta Lacks, whose cells were unknowingly taken for scientific research in the 1950s. The book explores the ethical implications of medical research and its impact on Henrietta's family",
        image: "",
        writer: "Rebecca Skloot",
        price: 1420,
    },
    {
        title: "The kite Runner",
        description: "Khaled Hosseini's novel is a poignant and powerful story of friendship, betrayal, and redemption set against the backdrop of Afghanistan. The narrative follows Amir, a young boy from Kabul, and his complex relationship with his friend Hassan.",
        image: "",
        writer: "Khaled Hosseini",
        price: 1330,
    },
    {
        title: "The Ocean at the End of the Lane",
        description: "Neil Gaiman's novel is a magical and nostalgic journey that blends fantasy and reality. The story follows an unnamed protagonist who returns to his childhood home and recalls a series of mysterious and otherworldly events from his past.",
        image: "",
        writer: "Neil Gaiman",
        price: 2160,
    },
    {
        title: "The Night Circus",
        description: "Erin Morgenstern's enchanting novel, The Night Circus, is a tale of magical competition and love. The story unfolds within the confines of a mysterious and fantastical circus that appears only at night. As two illusionists engage in a magical duel, the circus becomes a stage for wonder and romance.",
        image: "",
        writer: "Erin Morgenstern",
        price: 1400,
    },
    {
        title: "Educated",
        description: "Tara Westover's memoir, Educated, recounts her extraordinary journey from growing up in a strict and abusive household in rural Idaho with no formal education to earning a PhD from Cambridge University. The narrative explores the pursuit of knowledge, resilience, and breaking away from one's past.",
        image: "",
        writer: "Tara Westover",
        price: 2330,
    },
    {
        title: "The Silent Patient",
        description: "Alex Michaelides' psychological thriller, The Silent Patient, revolves around the mysterious case of Alicia Berenson, a celebrated painter who shoots her husband and then stops speaking. A criminal psychotherapist becomes obsessed with uncovering the truth behind her silence, leading to unexpected twists",
        image: "",
        writer: "Alex Michaelides",
        price: 2250,
    },
    {
        title: "Where the Crawdads Sing",
        description: "Delia Owens' novel is a captivating mystery and coming-of-age story set in the marshes of North Carolina. Where the Crawdads Sing follows the life of Kya Clark, known as the Marsh Girl, and intertwines a murder investigation with themes of nature, loneliness, and resilience.",
        image: "",
        writer: "Delia Owens",
        price: 2150,
    },
    {
        title: "The Goldfinch",
        description: "Donna Tartt's Pulitzer Prize-winning novel, The Goldfinch, tells the story of Theo Decker, who survives a terrorist attack at a museum and takes with him a small, captivating painting called The Goldfinch. The novel explores themes of loss, survival, and the power of art.",
        image: "",
        writer: "Donna Tartt",
        price: 1660,
    },
    {
        title: "The Song of Archilles",
        description: "Madeline Miller's novel brings to life the love story between Achilles and Patroclus in the context of the Trojan War. It's a beautifully written and moving tale that explores themes of love, fate, and the human condition.",
        image: "",
        writer: "Madeline Miller",
        price: 1400,
    },
    {
        title: "The Book Thief",
        description: "Markus Zusak's novel is set in Nazi Germany and narrated by Death. It follows the life of Liesel Meminger, a young girl who steals books and shares them with her neighbors and the Jewish man hidden in her basement. The novel is a powerful exploration of the impact of words and storytelling.",
        image: "",
        writer: "Markus Zusak",
        price: 1250,
    },
    {
        title: "The Power of Habit",
        description: "Charles Duhigg's nonfiction book delves into the science of habits, exploring how they work and how they can be transformed. It combines scientific research with real-life stories to provide insights into the patterns that shape our lives.",
        image: "",
        writer: "Charles Duhigg",
        price: 1414,
    },
    {
        title: "The Hitchhiker's Guide to the Galaxy",
        description: "Douglas Adams' classic science fiction comedy follows Arthur Dent, an unwitting Earthling who is swept off the planet just before it is destroyed to make way for a hyperspace bypass. The novel is a hilarious and satirical journey through space and time.",
        image: "",
        writer: "Douglas Adams",
        price: 665,
    },
    {
        title: "Pachinko",
        description: "Min Jin Lee's epic novel spans decades and follows the lives of multiple generations of a Korean family living in Japan. It explores themes of identity, love, and the impact of historical events on individuals and families.",
        image: "",
        writer: "Min Jin Lee",
        price: 1350,
    },
    {
        title: "To Kill a Mockingbird",
        description: "Harper Lee's masterpiece is a poignant exploration of racial injustice and moral growth in the American South during the 1930s. Through the eyes of Scout Finch, the novel addresses themes of empathy, compassion, and the search for justice.",
        image: "",
        writer: "Harper Lee",
        price: 1500,
    },
    {
        title: "The Hobbit",
        description: "J.R.R. Tolkien's classic fantasy novel takes readers on a journey with Bilbo Baggins, a hobbit who reluctantly becomes an adventurer. Filled with magical creatures, epic quests, and a richly imagined world, The Hobbit is a timeless tale of courage and discovery.",
        image: "",
        writer: "J.R.R. Tolkien",
        price: 1100,
    },
    {
        title: "1984",
        description: "George Orwell's dystopian novel 1984 paints a bleak vision of a totalitarian society where the government controls every aspect of citizens' lives. The novel explores themes of surveillance, propaganda, and the struggle for individual freedom.",
        image: "",
        writer: "George Orwell",
        price: 830,
    },
    {
        title: "The Catcher in the Rye",
        description: "J.D. Salinger's iconic novel follows the journey of Holden Caulfield, a disenchanted teenager who wanders through New York City. The novel explores themes of teenage angst, identity, and the challenges of growing up.",
        image: "",
        writer: "J.D. Salinger",
        price: 750,
    },
    {
        title: "Atomic Habits",
        description: "Written by James Clear, Atomic Habits is a bestselling self-help book that explores the power of tiny changes in building good habits, breaking bad ones, and mastering the tiny behaviors that lead to remarkable results. Clear delves into the science of habit formation, providing practical strategies and insights to help readers transform their habits and achieve lasting positive change",
        image: "",
        writer: "James Clear",
        price: 2500,
    },
];

module.exports = { data: sampleListings };